### ISSUE TITLE
View files on virtual file systems

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#238]

**Comment by viktor-podzigun** [comment]
Implementation details:
Before viewing, the file will be copied to the system temp directory, and will be removed on viewer exit.

**Comment by corporateshark** [comment]
How about large files?

**Comment by singalen** [comment]
I wonder if large LOCAL files are handled in a smart way by editor, viewer, syntax highlight...

**Comment by viktor-podzigun** [comment]
-- How about large files?

What do you mean? (I may guess you are talking about editing not viewing)

**Comment by corporateshark** [comment]
Editing is simple, just download all the stuff.
However, viewing is smart and can handle huge local files. Can it be implemented similarly for remote locations?

**Comment by viktor-podzigun** [comment]
Yes, as proposed, by copying the file to local temp folder (see above)

**Comment by corporateshark** [comment]
Ok, at least Far does the same thing.

**Comment by viktor-podzigun** [comment]
Closed via #461
