### ISSUE TITLE
Look into archive files

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#26]
Support common formats ( (zip, rar, etc)

**Comment by viktor-podzigun** [comment]
Is there any up to date thoughts about this issue? I think I could try to implement it.

Its only about reading/unpacking archives, not creating yet, right?

**Comment by corporateshark** [comment]
Yes, this is only about two steps:

* Browsing an archive in the panel
* Unpacking files

Take a look at the temp panel and this library https://github.com/libarchive/libarchive
This should be implemented as a File System.

**Comment by viktor-podzigun** [comment]
Thanks.

@helgp just read your comments on #361, how far are you on FSArchive?

**Comment by belonesox** [comment]
Sorry, is there any progress on this?

**Comment by viktor-podzigun** [comment]
Yes, I'm currently on it. I would say 20-25% already done. Will get back to it when have more free time, maybe on this week.

I will keep you updated on this issue.

**Comment by dmak** [comment]
Looking forward for this feature. I personally traverse into `.deb` and `.rpm` a lot.

**Comment by viktor-podzigun** [comment]
Feature is implemented (see PR #511).
You can checkout my dev branch to try it out:
https://github.com/viktor-podzigun/WalCommander/tree/feature/26_look_into_archive_files
