### ISSUE TITLE
Linux: submenu detaches from wcm after alt-tab

### ISSUE THREAD

**Issue by dizzy1984** [corporateshark/WCMCommander#306]
Here is an example http://i57.tinypic.com/5phd1t.png

**Comment by corporateshark** [comment]
Will check on OS X and Ubuntu.

**Comment by corporateshark** [comment]
OS X: unreproducable

**Comment by corporateshark** [comment]
@helgp Oleg, can you check this on Linux?

**Comment by corporateshark** [comment]
Can be related to the ``--dlg`` command line switch.

**Comment by helgp** [comment]
Confirming the Alt-tab problem on Linux. The problem does not exist on Windows.

On the other side, on Windows there is similar problem. Menu is detached when wcm window is drag-moved by its caption.

I am looking into. The idea is to capture certain system events (move, focus), and close menu on that.

**Comment by corporateshark** [comment]
WM_ACTIVATE?
