### ISSUE TITLE
After clicking one tool button, all toolbuttons lose tooltips.

### ISSUE THREAD

**Issue by singalen** [corporateshark/WCMCommander#309]
Tooltips reappear if I move the mouse to leave and re-enter toolbar area.

**Comment by corporateshark** [comment]
On what OS?

**Comment by singalen** [comment]
Ubuntu 14.10 x86_64.

**Comment by corporateshark** [comment]
@helgp Check Ubuntu, please.

**Comment by helgp** [comment]
Confirming on my Ubuntu 14.04 Linux

After left-clicking or right-clicking anywhere at the toolbar the tooltips are lost. Moving mouse out and in indeed restores tooltips.

The problem does not appear on Windows

The latest Wal-wcm (0.17.2) on my Linux shows exact the same problem.
