### ISSUE TITLE
Buttons/controls are drawn in a different font

### ISSUE THREAD

**Issue by singalen** [corporateshark/WCMCommander#319]
I have set all the fonts but last 3 "Help ..." to Droid Sans Mono 12.

Everything looks good except for some items are drawn in a clearly different (non-antialiased, for instance) font:
* "Ok/Cancel" buttons, other buttons and labels in most or all of the dialogs;
* Button bar.

Additionally, F2 user menu (main list body) is drawn with a different font size;

**Comment by corporateshark** [comment]
Is it still relevant?
