### ISSUE TITLE
Configurable color schemes

### ISSUE THREAD

**Issue by singalen** [corporateshark/WCMCommander#345]
Current styling system is a stub.
It would be great to have an external configuration files in `share` and pick color scheme from a user-defined styles list.
I'd love to see Solarized:http://ethanschoonover.com/solarized or SpaceGray:http://kkga.github.io/spacegray/.
More theming fun: http://iterm2colorschemes.com/

**Comment by corporateshark** [comment]
Can you tackle it?

**Comment by singalen** [comment]
When I have the time, no promises.
