### ISSUE TITLE
feature request : space acts as enter when button is in focus

### ISSUE THREAD

**Issue by dizzy1984** [corporateshark/WCMCommander#352]

**Comment by corporateshark** [comment]
@helgp  Do we really need to add this feature?

**Comment by singalen** [comment]
I believe it was in http://en.wikipedia.org/wiki/IBM_Common_User_Access

**Comment by helgp** [comment]
Whoseem

I will add this after finishing tmp panel.

**Comment by dizzy1984** [comment]
yeah, i am use to it, please!

**Comment by corporateshark** [comment]
Ok, just make sure it does not break anything.
