### ISSUE TITLE
File attributes: modification of creation/modification/access time

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#375]

**Comment by corporateshark** [comment]
@helgp @singalen 
This needs to be tested on Linux.

**Comment by singalen** [comment]
Works fine, thanks! Some minor notices below.

![image](https://cloud.githubusercontent.com/assets/151199/6937978/78db1a42-d868-11e4-9631-3c2fc68cc3c9.png)

* Date textboxes are 1 letter short. Or 2 letters, as it's possible now to pusition cursor one char after the text - this shouldn't be possible if a textbox has a maximum length.
* Do we actually need milliseconds?
* Tab order is "date-date-date-time-time-time"  while it should be "date-time-date-time-date-time".
* Control spacing for checkboxes and for these time boxes is different, this looks a bit ugly (well, the checkboxes are too dense too).

**Comment by corporateshark** [comment]
>>Date textboxes are 1 letter short. Or 2 letters, as it's possible now to pusition cursor one char after the text - this shouldn't be possible if a textbox has a maximum length.

Yep, I will fix the Linux layout.

>>Do we actually need milliseconds?

On Windows, yes, it is a part of WinAPI. On other platforms, not sure. Probably we don't.

>>Tab order is "date-date-date-time-time-time" while it should be "date-time-date-time-date-time".

Cannot fix it right now, but the problem is well defined.

>>Control spacing for checkboxes and for these time boxes is different, this looks a bit ugly (well, the checkboxes are too dense too).

Will fix the layout and we will see what else can be done.

**Comment by corporateshark** [comment]
9152f0b216e77c341a8db8176aa347e4c165b8e7
0f661715b56945bc1542a123f8575de8ced39453
