### ISSUE TITLE
File attributes functionality does not work on items in temporary panel

### ISSUE THREAD

**Issue by helgp** [corporateshark/WCMCommander#377]
The FA action should change attributes for files on _base_ filesystem.

- Add FSTmp::StatSetAttr override passing the action to base FS.
- Rethink URL scheme for FSTmp to have consistency between every FSTmp object and its URL. This is maintained by Parze*() and FSTmp::Uri() functions.

**Comment by corporateshark** [comment]
A good reason to refactor all ``Parze*()`` functions using ``urlparser``. See ``ParzeFtpURI()`` for a decent sample.
