### ISSUE TITLE
FR: Add an option configurable at GUIs to enable inheriting the current dir from a parent process

### ISSUE THREAD

**Issue by egphilippov** [corporateshark/WCMCommander#379]
So that the current panel would show the contents of the current dir that was at the process that launched the wcm at the time of launch. IMHO it is not very important if this option is present at Far. This option is useful IMNSHO.

**Comment by helgp** [comment]
An idea for implementing the above.

wcm on UNIX may be invoked in two modes: from Windows Manager by clicking proper icon, or by typing 'wcm' at a shell prompt. "Current dir" context appears to be applicable only for the shell prompt invocation. 

The WCM may determine who is invoking it. Only if the invoker is an interactive shell, load current dir to the active panel.

**Comment by corporateshark** [comment]
@helgp Is there a decent API to do that?

**Comment by helgp** [comment]
The simplest idea is to check whether WCM parent application name (from the file /proc/getppid()/cmdline) ends with 'sh'. Any failure during the determination process should result in falling back to the existing behavior - to be safe.

**Comment by corporateshark** [comment]
@helgp Should this http://stackoverflow.com/a/298518 do the trick?

**Comment by helgp** [comment]
Sure, the getcwd() will do the job. I would use MAX_PATH+1 instead of It hard-coded 1024 from the sample. It is POSIX, therefore, is portable.

BTW, another way to distinct WM vs cmdline launches is to .. add some command line switch to wcm.desktop file, and check the switch on wcm startup. --lauched-from-wm?

**Comment by singalen** [comment]
The switch looks completely unclear. I'd rather do `alias wcm=wcm --inherit-current-dir` in `.bashrc`.

**Comment by corporateshark** [comment]
@singalen This one is actually a better solution since we want to stick to that behavior of FAR Manager when it opens the last visited folders from the previous session.
