### ISSUE TITLE
escShellStr() is not UTF8-aware

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#421]
Use ``utf8proc_iterate()`` to iterate code points and escapify accordingly.

**Comment by helgp** [comment]
@corporateshark, do you have a test case in mind that fails?

**Comment by corporateshark** [comment]
How about this?

```
Mylene Farmer - L'antre.MP3
MYLENE FARMER - L`AME-STRAM-GRAM.mp3
```

**Comment by helgp** [comment]
The above names fail to open  on 'Panel Enter' (original Wal Unicode function). Both names open just fine with 'Panel Shift-Enter' (new UTF8 function that uses escShellStr()). I am adding escaping to the Unicode function.
