### ISSUE TITLE
Temporary panel should have .. item to go back to last directory.

### ISSUE THREAD

**Issue by singalen** [corporateshark/WCMCommander#436]
A feature that does exist in FAR.

**Comment by helgp** [comment]
How does it work in Far?

**Comment by corporateshark** [comment]
@helgp probably he is talking about the ``..`` item at the very beginning of a temp panel. Once you press ``Enter`` on this item, you end up in the last opened directory.

**Comment by singalen** [comment]
Exactly.

**Comment by corporateshark** [comment]
This is especially annoying if the panel is empty.
