### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#441]
OS X. Debug output in the console:

``'/usr/share/wcm/styles/0.style' (No such file or directory)``

**Comment by singalen** [comment]
It's normal if there's an old configuration version. It will go when you select and save a style in Styles settings.

**Comment by corporateshark** [comment]
But it is confusing.

**Comment by singalen** [comment]
Well, there should be some way to tell that a theme file is broken - for instance, for color theme authors. It could be stderr or red a window - whichever you prefer.

**Comment by corporateshark** [comment]
Then the message should be improved to tell users what to do with it.

**Comment by singalen** [comment]
It's the parser's exception message, so it should be pretty informative. Currently, it's pretty correct, just appears when it shouldn't.
Let me eliminate it for now - it will appear only if someone deletes the saved theme by hand.

**Comment by corporateshark** [comment]
Ок. Just close this once it is fixed.
