### ISSUE TITLE
OS X: Display contents of /Volumes folder in Select Drive dialog (when press Alt+F1/F2)

### ISSUE THREAD

**Issue by viktor-podzigun** [corporateshark/WCMCommander#442]
On Mac when USB drive (or image file) is mounted it appears in /Volumes folder. It would be useful to access them through Select Drive dialog, when press Alt+F1/F2.

**Comment by corporateshark** [comment]
Platform-specific but very useful. Can be a nice feature, but should have an option to turn it off.

**Comment by corporateshark** [comment]
Btw, Linux can also benefit from it.

**Comment by viktor-podzigun** [comment]
Closed via  #446
