### ISSUE TITLE
File view/edit history doesn't work for temp panel items

### ISSUE THREAD

**Issue by viktor-podzigun** [corporateshark/WCMCommander#443]
It would be useful to remember view/edit positions/history for files put on temp panel.

**Comment by viktor-podzigun** [comment]
Desired behavior (use cases) for editor (the same applies for viewer):
- User edits the file on local FS -> last position stored in history (1);
- User searches for the same file -> put on Temp panel;
- User edits the same file from the Temp panel -> editor opens at the lat edit position (1), after editing last position stored in history (2);
- User edits the same file from the Temp panel again -> editor opens at the last edit position (2);
- OR user edits the same file from local system -> editor opens at the last edit position (2);

**Comment by corporateshark** [comment]
Looks like an indirection scheme and file aliases.

**Comment by viktor-podzigun** [comment]
Yes, FAR does the same :D
From the user prospective it works with the same physical files.
