### ISSUE TITLE
Files disapears from temp panel after editing

### ISSUE THREAD

**Issue by viktor-podzigun** [corporateshark/WCMCommander#444]
**OS X**

Steps to reproduce:
1. Search for files (Alt+F7)
2. Press Panel button to put found files on temp panel
3. Open editor (F4) for any file from temp panel
4. Press F2

As a result: selected file disappears from temp panel.
Expected behavior: file should be kept on temp panel.

**Comment by viktor-podzigun** [comment]
Forgot to mention that this was found on OS X. Today tested it on Windows - it works.

**Comment by helgp** [comment]
OS X-ers, please, test.

**Comment by viktor-podzigun** [comment]
Will be able to check at the evening.

**Comment by viktor-podzigun** [comment]
Checked #459 on OS X, works fine, files not disappearing anymore after editing and saving, and .. also works.
