### ISSUE TITLE
Option for copying command line contents

### ISSUE THREAD

**Issue by viktor-podzigun** [corporateshark/WCMCommander#447]
The issue is that there is a way to past text to command line, but when you copy it back the current file path is copied instead, in Panel mode.

It would be useful if WCM has configurable panel option to allow copy command line text on Ctrl+C (Ctrl+Insert) instead of selected file path, if command line is not empty.

**Comment by singalen** [comment]
For me, on Linux
* Ctrl-Ins always copies the command line contents. If it's empty, it copies the selected or a current file name, without a path. 
* Ctrl-C does nothing, and I'm OK with it: it's a conventional `SIGTERM` hotkey on all systems.
It's pretty consistent, as for me.

**Comment by viktor-podzigun** [comment]
How about OS X? There is no Insert key on the keyboard :D

**Comment by corporateshark** [comment]
``CMD-C`` should work there as well.

**Comment by viktor-podzigun** [comment]
It should, but it doesn't. Thats the issue about. The same for Win.

To copy command line contents, currently, you need to do the following:
- enter or paste text to the command line;
- press Ctrl+O;
- press Ctrl+A;
- finally press Ctrl(CMD on OS X)+C;
