### ISSUE TITLE
OS X: CMD+C not working for command line in panel mode

### ISSUE THREAD

**Issue by viktor-podzigun** [corporateshark/WCMCommander#458]
Currently CMD+C copies empty line to clipboard.

Expected behavior:
- if command line is not empty CMD+C should copy all command line contents to clipboard;
- if command line is empty CMD+C should copy current/selected file name with extension.

**Comment by corporateshark** [comment]
On OS X both CMD+C and Ctrl+C should do the same thing (so full-size non-Apple keyboards can be used equally easily).

**Comment by viktor-podzigun** [comment]
Sure.

**Comment by amitin** [comment]
Disagree. 'Ctrl-C' is not a key combination to perform copying to a clipboard
on OS X. For non-Apple keyboards 'Win' key acts as 'Command' key, so
'Win-C' would work there.

> On OS X both CMD+C and Ctrl+C should do the same thing (so full-size
> non-Apple keyboards can be used equally easily).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/corporateshark/WCMCommander/issues/458#issuecomment-90490121>
> .
>


-- 
Alexander Mitin

**Comment by corporateshark** [comment]
It does, but it is unconvenient for rapid reflex-based use.

**Comment by amitin** [comment]
Still disagree. :-) You cannot do your rapid reflex-based use for other native apps (don't you use WCMCommander only?), so you're forced to change your reflexes anyway. Moreover, I'm sure you know that 'Ctrl+C' key combination is reserved for sigint under *nix-like systems.

**Comment by corporateshark** [comment]
@amitin yes I do, this is the reason why I'm so interested in the project.
