### ISSUE TITLE
Linux: Hotkeys conflict in select drive dialog 

### ISSUE THREAD

**Issue by helgp** [corporateshark/WCMCommander#471]
![hotkeys-conflict](https://cloud.githubusercontent.com/assets/8525021/7240958/47b4943c-e783-11e4-8a49-5ea0b4f206a0.png)

See: 1,2,3 hotkeys are used in both halves of the dialog.

OSX-ers, can we use A, B, C,... for the mount point shortcuts instead of numbers? It appears that the 'mount points' are not applicable on Windows, and 'drive letters' are not applicable on Linux - so we do not have conflict on these two platforms.

**Comment by corporateshark** [comment]
On Windows, there should be A, B... letters as drive shortcuts.
