### ISSUE TITLE
Windows: segfault on exit when launched from cygwin/mingw terminal (mintty)

### ISSUE THREAD

**Issue by helgp** [corporateshark/WCMCommander#479]
To reproduce. 
On current wcm:
- Start mintty terminal (from cygwin32, cygwin64 or mingw-msys)
- Start wcm from command line of the terminal
- F10-exit from the wcm

Upon exit the error is "Access violation writing location 0x00000014" with the following stack trace:
![wcm-stack](https://cloud.githubusercontent.com/assets/8525021/7304950/749641a2-e9c8-11e4-8ca3-0be66685f6de.png)

The 'mutex_lock' function in the trace is:
inline int mutex_lock( mutex_t* m ) { EnterCriticalSection( m ); return 0; }

The problem does not appear when wcm is launched from cmd command line, or from Explorer.

The problem is reliably reproduced on 32-bit Visual Studio builds with the provided MSVC project file under VS2013-update5, from the sources at least since 2015-Feb-12. All 64-bit Windows releases (0.17, 0.18, and 0.19), as well as 32-bit original WCM binary appear to be unaffected.

Any ideas?

**Comment by corporateshark** [comment]
Can you run Far from Cygwin?
Can you build using MinGW (for example, GCC 4.9.2 http://www.equation.com/servlet/equation.cmd?fa=fortran) and try it? If the problem is not reproduced with MinGW builds, it can be a problem of MSVC and Cygwin compatibility.

**Comment by helgp** [comment]
mintty doc states that Far Manager can not be started from the mintty at all:
http://conemu.github.io/en/CygwinMsys.html
because of Far console nature. This should not apply to wcm.

**Comment by corporateshark** [comment]
How about WCM built with MinGW?

**Comment by helgp** [comment]
I believe that I understand source of the problem. It is due to uncontrollable order of destructor calls for global objects. The scenario is:

- there are global cicon objects in the code : panel.cpp: folderIcon, and folderIconHi
- cicon destructor uses another global object: swl_wincore.cpp:iconCopyMutex
- on wcm exit, the iconCopyMutex is destroyed first
- cicon destructor is called next. It tries to use the destroyed iconCopyMutex, and fails
- the above stack shows the failure

**Comment by corporateshark** [comment]
Can we move all these global objects into ``globals.h`` (already there) and control their lifetime explicitly?

**Comment by helgp** [comment]
Done in the suggested globals.cpp way. Also, static file-scope objects are converted to private static class-scope objects. This is done to prevent global namespace pollution.
