### ISSUE TITLE
Make Linux binaries for 0.20.0

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#483]
The version ``0.20.0`` is packed with new features and looks pretty stable to be released. We need to build the binaries for Linux.

Use the ``release-0.20.0`` branch.

**Comment by helgp** [comment]
I would suggest to merge PR #484 to this release. Seeing an error message on every wcm start is annoying.

**Comment by corporateshark** [comment]
Looks good, done.

**Comment by helgp** [comment]
http://divgrad.com/walcommander/wcm_0.20.0-1_amd64.deb
http://divgrad.com/walcommander/wcm_0.20.0-1_i386.deb
http://divgrad.com/walcommander/wcm-0.20.0-2.x86_64.rpm
http://divgrad.com/walcommander/wcm-0.20.0-2.i386.rpm
