### ISSUE TITLE
Reproduciable crashed on GNOME SHELL when ALT-TAB to other application

### ISSUE THREAD

**Issue by belonesox** [corporateshark/WCMCommander#486]
wcmcommander-0.20.0-1
Reproduciable crashed on GNOME SHELL when ALT-TAB switch to other application
See. https://vimeo.com/126241420
Reproduciable always.

On KDE — OK.

walcommander-0.19.0.1  works without such crash.

Tested crash on Gnome Shell 3.12 and Gnome Shell 3.16.

**Comment by belonesox** [comment]
Hm. Crash reproduced from branch release-0.20.0
but not crashed when compiled from HEAD.

**Comment by aylubimov** [comment]
Reproducible on x86 CentOS 6.5 GNOME SHELL 3.16, compiled from HEAD 2 days ago (04/28/15).

**Comment by belonesox** [comment]
>>but not crashed when compiled from HEAD.
Sorry. HEAD version also crashed. (I dont know how it not crashed when I tested it, now it crashed always).

**Comment by corporateshark** [comment]
@belonesox any chance to find the bad commit by bisecting?

**Comment by helgp** [comment]
I have reproduced the problem on one of my test VMs: Debian8 3.16.0-4-amd64. Should be an easy fix.
