### ISSUE TITLE
"Start in this terminal" in file associations does not work after refactoring

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WCMCommander#488]
Seems terminal attachment is completely broken not only in file associations. This is a major regression and commands are not executed properly any more.

**Comment by viktor-podzigun** [comment]
How to reproduce?

**Comment by corporateshark** [comment]
I have an ``mpg123`` tool binded to ``*.mp3`` files to play them by Enter.

**Do**

1) create a file association ``*.mpg``
2) add a command there ``mpg123 !.!``
3) uncheck ``Start in this terminal``
4) go to your music collection and start an mp3 file. 

**Observe**

The mpg123 runs in the WCM terminal essentially blocking it.

**Should be**

WCM terminal is not blocked.


The last working commit in master 786f851e09fe6082f182fe54a6561dbfc23687a

**Comment by corporateshark** [comment]
P.S. I checked out the new logic, the ``NoTerminal`` parameter is not passed properly and lately is ignored.

**Comment by viktor-podzigun** [comment]
Right, NoTerminal param doesn't passed further, sorry for that stupid bug, created PR#489 with the fix.

**Comment by corporateshark** [comment]
Now I see the ``mpg123`` command output in the parent terminal as it should be. However, WCM terminal is still blocked and I cannot return to panels.

**Comment by corporateshark** [comment]
@viktor-podzigun any ideas?
