### ISSUE TITLE
Alt+Tab closes commander

### ISSUE THREAD

**Issue by yurtsevich** [corporateshark/WCMCommander#501]
First of all, thanks for your work. But I'm facing one problem. It's not so critical but annoying. So:

Mint 17.2
WCM Commander v 0.20.0 (Apr 24 2015  17:54:01 via GCC 4.8.2 for Linux64)

When WCM is current window and Alt+Tab is pressed (intending to switch to another window), this leads to closing WCM being just opened. In syslog there's following error message:

wcm[7744]: segfault at 18 ip 00000000004f44f3 sp 00007fff0b51a1c0 error 4 in wcm[400000+224000]

**Comment by corporateshark** [comment]
Can you try the latest version from GitHub?
