### ISSUE TITLE
Add check-box "Process multiple folders" in Create directory dialog (F7)

### ISSUE THREAD

**Issue by viktor-podzigun** [corporateshark/WCMCommander#514]
As a User I would like to be able to create multiple sub-directories, by separating them by slash (/) when create new directory.

**Comment by corporateshark** [comment]
Do you mean by ``,``? Check out the ``clMultimaskSplitter`` class.

**Comment by viktor-podzigun** [comment]
This is exactly the same feature that FAR has. There directories separated by '/' as usual.
The flow is:
* you copy some full path, like /dir1/dir2/dir3
* past it to edit box in the Create directory dialog
* check "Process multiple folders" checkbox

When you press Enter (or OK button) the specified directories structure created under the current open folder. That's it.

**Comment by corporateshark** [comment]
Sounds good. Please, proceed.
