### ISSUE TITLE
License story

### ISSUE THREAD

**Issue by techtonik** [corporateshark/WCMCommander#524]
LICENSE file contains clause:
```
Based on Wal Commander (c) Valery Goryachev
http://www.wal-commander.org
```

You can't base codebase with MIT license on proprietary code with different license the same way you can't base MIT code on GPL. So can you explain the whole story - how did you manage to fork off the proprietary project?

**Comment by corporateshark** [comment]
The upstream changed it's licence to proprietary in 2015.

**Comment by techtonik** [comment]
@corporateshark do you have a copy of original source code to validate the fact that original license was MIT compatible?

**Comment by corporateshark** [comment]
The original license was not MIT. The original author granted permission for the fork in 2014 and was collaborating with the project. In 2015 he quit any collaboration with the fork, put a new proprietary license on the upstream and claimed the fork is now unauthorized. Here are some examples of his collaboration with the fork on GitHub: https://github.com/corporateshark/WCMCommander/issues/215
https://github.com/corporateshark/WCMCommander/issues/218
The account is now removed and you might want to contact GitHub support if you want clarifications on the origins of that account.

**Comment by techtonik** [comment]
I am not interested in personal conflicts. The question is if the original license was open source license (as approved by OSI) or not? Do you have the exact text for it? It may be incompatible with MIT license that you've chosen.

**Comment by corporateshark** [comment]
I have explained my position in the message just above yours. Feel free to contact other parties.

**Comment by techtonik** [comment]
@corporateshark again, it is not you and that guy. It is a legal question if the MIT license for this project is valid. If you can not prove it, then anybody using or shipping your project can be a subject of legal action. You need the exact license text as it was distributed with original sources.

The fact is that you can not grant all the rights you want with MIT license if original author didn't give them to you.

**Comment by techtonik** [comment]
"permission for the fork" is only one right, and there are many others that are mentioned in your license text.

**Comment by helgp** [comment]
@techtonik 

I believe that you had a context to start the thread. Could you share the context?

**Comment by techtonik** [comment]
@helgp I need an open source file manager for Linux, which I can extend without legal problems.

**Comment by helgp** [comment]
@techtonik

Main problem with the WCM is far from being in legal aspect. The original codebase is based on a homebrewn API with noticeable amount of undocumented side effects. Author of the API might be able to keep all these in mind, though side developers (including myself) have to lean that in a hard way. The only rational complain that the original author have exposed when closing upstream sources was usage of STL for base API in the fork.

While the codebase does not have legal problems, you may not enjoy too much contributing to the project. In addition to opposition from the original author, you may be bored by a feedback of aged orthodox-FM community.

**Comment by techtonik** [comment]
> Main problem with the WCM is far from being in legal aspect. 

@helgp this ticket is about legal aspect. =)

**Comment by techtonik** [comment]
> While the codebase does not have legal problems

So far nobody provided the proof.

**Comment by techtonik** [comment]
So, in the absence of feedback, the facts are that MIT license stated by WCMCommander is not valid, because rights to relicense initial code were not granted by original contributor. Therefore this fork is an ongoing copyright violation, and as such it can not be used in official Debian distribution or derivatives.
