### ISSUE TITLE
WCMC closes after Alt-Tab

### ISSUE THREAD

**Issue by likov** [corporateshark/WCMCommander#525]
Hello. WCM Commander suddenly closes without warnings after pressing Alt-Tab to switch from WCMC to anything else. Switching apps using mouse, switcthing to WCMC works well.

Linux Mint 17.1 Rebecca, MATE-64.

wcm_0.20.0-1_amd64.deb

**Comment by helgp** [comment]
Dup of #523, #501, #499, and #486 

The issue is fixed in the 'head' revision. Do a rebuild it from the most recent sources, and you are GTG.
