### ISSUE TITLE
File association problem

### ISSUE THREAD

**Issue by IvanAli** [corporateshark/WCMCommander#530]
I try to associate C++ files using the following command when Enter is pressed: g++ !.! -o ! -g

But then, when the command is run for some file (let's call it file.cpp) this is how it is interpreted:
g++ "file.cpp" -o ! -g

That is, the ! for the -o flag was not replaced

**Comment by corporateshark** [comment]
Take a look into ``MakeCommand()`` in ``string-util.cpp``.
